# Generated by Django 4.1.7 on 2023-04-10 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.IntegerField(default='NULL', null=True)),
                ('Speciality', models.IntegerField(default='NULL', null=True)),
                ('Major', models.IntegerField(default='NULL', null=True)),
                ('IsCompulsory', models.IntegerField(default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.IntegerField(default='NULL', null=True)),
                ('Course_Name', models.TextField(default='NULL', null=True)),
                ('Credit', models.IntegerField(default='NULL', null=True)),
                ('Semester', models.IntegerField(default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.IntegerField(default='NULL', null=True)),
                ('PrerequisitID', models.IntegerField(default='NULL', null=True)),
                ('PrerequisitsGroup', models.IntegerField(default='NULL', null=True)),
                ('TakeTogether', models.IntegerField(default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.BigIntegerField(default='NULL', null=True)),
                ('Semester', models.IntegerField(default='NULL', null=True)),
                ('Course', models.IntegerField(default='NULL', null=True)),
                ('GradeID', models.IntegerField(default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentMajorMinor',
            fields=[
                ('SID', models.BigIntegerField(default='NULL', primary_key=True, serialize=False)),
                ('Special', models.IntegerField(default='NULL', null=True)),
                ('Major', models.IntegerField(default='NULL', null=True)),
                ('Minor', models.IntegerField(default='NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notes',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
